version: '3'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify-data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.de
      PGADMIN_DEFAULT_PASSWORD: postgres

  app:
    build: .
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES__HOST: db
      POSTGRES__PORT: 5432
      POSTGRES__USER: postgres
      POSTGRES__PASSWORD: postgres
      POSTGRES__DATABASE_NAME: spotify-data
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload" ]